### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'docs/html/readme.html'

### ISSUE THREAD

**Issue by wiwski** [eli64s/PydocsAI#1]
Hey, just trying this repo as I really like the idea of using davinci to generate doc.

Here is a bug I found while running `src/main.py` :

```
  File "/home/.../PydocsAI/src/utils.py", line 38, in write_html
    with open(self._get_file_path(file_name), "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'docs/html/readme.html'
```

I think this is because `docs/html` is not there when pulling the repo :)

**Comment by eli64s** [comment]
Hey, thanks for checking out the project! Made a lot of updates today - including removing the HTML file writing. 

Let me know if you're experiencing any additional bugs. Thank you.
